services:
    hx:
        command: elixir --sname hx -S mix run --no-halt

        depends_on:
            - hx-db

        environment:
            HX_DATABASE_URL: postgres://postgres:postgres@hx-db:5432/hx

            HX_SECRET_KEY: menNeYNhHWnga6At2BtYn7ypwcctOIRrsQFIKj2MOoWMoRYwFzQGTc0J+N5FL/gm

            HX_SIGNING_SALT: ErUm6yqmZzbNHwsUWnMzg0N5BncDEbyN

        image: ghcr.io/hxpm/elixir:1.15.6

        ports:
            - 4000:4000

        volumes:
            - source: ../

              target: /usr/local/src/hx

              type: bind

            - source: hx-build

              target: /usr/local/src/hx/_build

              type: volume

            - source: hx-deps

              target: /usr/local/src/hx/deps

              type: volume

            - source: hx-node-modules

              target: /usr/local/src/hx/node_modules

              type: volume

        working_dir: /usr/local/src/hx

    hx-db:
        environment:
            POSTGRES_PASSWORD: postgres

        image: postgres:16.0

        volumes:
            - source: hx-db

              target: /var/lib/postgresql/data

              type: volume

version: "3.9"

volumes:
    hx-build:
    hx-db:
    hx-deps:
    hx-node-modules:
