services:
    hx:
        depends_on:
            - hx-db

        environment:
            HX_DATABASE_URL: postgres://postgres:postgres@hx-db:5432/hx

            HX_SIGNING_SALT: ErUm6yqmZzbNHwsUWnMzg0N5BncDEbyN

        image: ghcr.io/hxpm/elixir:1.14.4

        volumes:
            - source: ../

              target: /usr/local/src/hx

              type: bind

            - source: hx

              target: /usr/local/src/hx/_build

              type: volume

            - source: hx

              target: /usr/local/src/hx/deps

              type: volume

        working_dir: /usr/local/src/hx

    hx-db:
        environment:
            POSTGRES_PASSWORD: postgres

        image: postgres:15.2

        volumes:
            - source: hx-db

              target: /var/lib/postgresql/data

              type: volume

version: "3.9"

volumes:
    hx:
    hx-db:
