name: ci

on:
    - push

jobs:
    check-commit:
        name: Check

        uses: hxpm/gha/.github/workflows/check-commit.yaml@main

    compute-cache-key:
        name: Compute

        uses: hxpm/gha/.github/workflows/elixir-compute-cache-key.yaml@main

        with:
            docker-service: hx

    check-format:
        name: Check

        needs:
            - check-commit
            - compute-cache-key

        uses: hxpm/gha/.github/workflows/elixir-check-format.yaml@main

        with:
            cache-key: ${{ needs.compute-cache-key.outputs.cache-key }}

            docker-service: hx

            project-name: hx

    check-functionality:
        name: Check

        needs:
            - check-commit
            - compute-cache-key

        uses: hxpm/gha/.github/workflows/elixir-check-functionality.yaml@main

        with:
            cache-key: ${{ needs.compute-cache-key.outputs.cache-key }}

            docker-service: hx

            project-name: hx

    check-types:
        name: Check

        needs:
            - check-commit
            - compute-cache-key

        uses: hxpm/gha/.github/workflows/elixir-check-types.yaml@main

        with:
            cache-key: ${{ needs.compute-cache-key.outputs.cache-key }}

            docker-service: hx

            project-name: hx

    check-xref:
        name: Check

        needs:
            - check-commit
            - compute-cache-key

        uses: hxpm/gha/.github/workflows/elixir-check-xref.yaml@main

        with:
            cache-key: ${{ needs.compute-cache-key.outputs.cache-key }}

            docker-service: hx

            project-name: hx
